
import Navbar from '../components/Navbar';
import Head from 'next/head'
import InitialPage from "../components/InitialPage/index"
import { useSelector } from 'react-redux';
import { selectColorMode } from '../reducers/colorMode/colorModeSlice';



export default function Home() {

  const ColorTheme = useSelector(selectColorMode);



  return (
    <div className={`${(ColorTheme ===false) ? 
     (`bg-white`) : (`bg-gradient-to-r from-gray-800 via-gray-500 to-gray-800
      text-purple-200`)}`}>
      <Head>
        <title>Boogle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://cdn3.iconfinder.com/data/icons/letters-and-numbers-1/32/letter_B_red-512.png" />
      </Head>
      <header className=''>
        <Navbar/>
      </header>
      <main className="flex justify-center xl:justify-around xl:pr-[3vw]">
        <InitialPage/>
        
      </main>
     
    </div>
  )
}
