
import Navbar from '../components/Navbar';
import Head from 'next/head'
import InitialPage from "../components/InitialPage/index"
import SearchResultSites from '../components/SearchResultSites';
import RelatedSearch from '../components/RelatedSearch';
import BooglePagination from '../components/BooglePagination';


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Boogle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar/>
      </header>
      <main className="flex justify-center xl:justify-around xl:pr-[3vw]">
        <InitialPage/>
        
      </main>
      <footer>

      </footer>
    </div>
  )
}
